fabric8-analytics/fabric8-analytics-worker

cucoslib/dispatcher/nodes.yml, cucoslib/process.py, cucoslib/storages/__init__.py, cucoslib/storages/s3_mavenindex.py
Needed by https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/2
=> S3MavenIndex storage

openshift/template.yaml
Full error message:
error: unable to decode "template.yaml": [pos 4709]:
json: expect char '"' but got char '1'
=> [openshift] Fix "unable to decode" error

cucoslib/workers/code_metrics.py
=> Average of averages is not average

openshift/template.yaml
So we can safely scale to 30 workers.
=> [openshift] Limit CPU to 500m

cucoslib/data_normalizer.py, cucoslib/enums.py, cucoslib/graphutils.py, cucoslib/solver.py, cucoslib/utils.py
This changeset just fixes several errors reported by the PEP8 checker. It does not change the program logic at all, just makes sure we'd follow standards ;)
=> Fix several errors reported by PEP8 checker

tests/storages/test_postgres.py, tests/test_blackduck_helpers.py, tests/test_data_normalizer.py, tests/test_pulp.py, tests/test_schemas.py, tests/test_utils.py, tests/workers/test_downstream.py, tests/workers/test_licensecheck.py
This is another set of small fixes to make PEP8 reporter happy, now all changes have been made in tests (/tests subdirectory).
=> Fix PEP8 errors in tests

cucoslib/dispatcher/flows/bayesianFlow.yml
This reverts commit df2a4f7e2d8fa5d6074ecda5f9e474189aabe54e.
=> Revert "Disable graph imports"

cucoslib/setup_celery.py, cucoslib/start.py
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/47
=> Decouple Selinon and Celery initialization

cucoslib/process.py, cucoslib/workers/cvedbsync.py
workaround for https://github.com/snyk/vulnerabilitydb/issues/14
=> [CVEDBSyncTask] clone develop branch of snyk vulndb repo

cucoslib/utils.py, cucoslib/workers/license.py
=> [LicenseCheckTask] make sure username is set

f8a_worker/dispatcher/flows/stackApiGraphV2Flow.yml, f8a_worker/dispatcher/nodes.yml, f8a_worker/graphutils.py, f8a_worker/workers/__init__.py, f8a_worker/workers/recommender.py, f8a_worker/workers/stackaggregator_v2.py
This is still R&D. It needs to be more robust and remove some hardcodedness.
=> Initial drop for intent based recommendation

alembic/versions/a31c98c74ea0_add_e_p_v.py, alembic/versions/b4fbc8e04c81_gh_usage_with_versions.py, f8a_worker/data_normalizer.py, f8a_worker/enums.py, f8a_worker/process.py, f8a_worker/solver.py, f8a_worker/workers/CVEchecker.py, f8a_worker/workers/anitya.py, f8a_worker/workers/dependency_snapshot.py, f8a_worker/workers/downstream.py, f8a_worker/workers/license.py, f8a_worker/workers/mercator.py, f8a_worker/workers/schemas/metadata.py, hack/install_deps_rpm.sh, requirements.in, requirements.txt, tests/conftest.py, tests/data/dataNormalizer/nuspec-expected, tests/data/dataNormalizer/nuspec-from-mercator, tests/data/nuget/nuspec/jQuery.UI.Combined.nuspec, tests/test_data_normalizer.py, tests/test_process.py, tests/test_solver.py, tests/test_utils.py, tests/workers/test_cvecheck.py
=> Add nuget ecosystem

f8a_worker/solver.py, tests/test_solver.py
Failing `test_pypi` is expected - to show that `PypiSolver` is wrong and needs to be fixed.
=> Fix PypiSolver

f8a_worker/dispatcher/flows/bayesianPackageAnalysisFlow.yml, f8a_worker/dispatcher/nodes.yml, f8a_worker/solver.py, f8a_worker/workers/__init__.py, f8a_worker/workers/githuber.py, f8a_worker/workers/libraries_io.py, tests/workers/test_libraries_io.py
Scrape some basic statistics from https://libraries.io
=> Libraries.io task

f8a_worker/workers/githuber.py, f8a_worker/workers/schemas/github_details.py, tests/data/schemas/github_details-v2-0-0.schema.json, tests/workers/test_githuber.py
The API rate limit is very lean - 30 requests per minute.
=> Stop collecting data via GitHub's Search API

f8a_worker/data_normalizer.py, f8a_worker/utils.py
=> [DataNormalizer] treat download-url as code_repository

f8a_worker/workers/license.py
With this scanning of [pypi/tensorflow-gpu](https://pypi.python.org/pypi/tensorflow-gpu) takes 'only' 6 minutes instead of 11 minutes.
=> [LicenseCheckTask] ignore *.so files

f8a_worker/workers/libraries_io.py, tests/workers/test_libraries_io.py
* give more details about top dependent repositories
* get machine-readable date/time from datetime attribute
=> LibrariesIoTask improvements

f8a_worker/process.py
=> Descriptive error when there's no release file

openshift/template.yaml
=> [openshift/template.yaml] increase memory limit to 1200Mi due to scancode

f8a_worker/workers/mercator.py
=> [MercatorTask] .egg-info/ can be under src/

f8a_worker/solver.py, tests/test_solver.py
=> [PypiReleasesFetcher] if failure, try again with swapped case of first letter

f8a_worker/dispatcher/nodes.yml
Fixes issue https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/141
=> Added proper server side encryption for user profile bucket

f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/151
=> Disable code_metrics and digests tasks

f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/152
=> Do not run license task for nuget ecosystem

f8a_worker/workers/sentiment_scorer.py
Unnecessary print() statement in sentiment_scorer.py file is removed.
=> remove unrequired print statement

f8a_worker/workers/sentiment_scorer.py
Hi,
This PR mainly contains the logging in sentiment-scorer.py file. However, it also has a small shuffling of import files to make them more readable.
Thanks,
Saket
=> include log msgs. in sentiment-scorer.py file.

Dockerfile, Dockerfile.tests, hack/install_deps_npm.sh, hack/install_deps_rpm.sh, tests/workers/test_binwalk.py, tests/workers/test_linguist.py, tests/workers/test_oscryptocatcher.py
Reduces image size 2.2 GB -> 1.6 GB
=> Don't install unused dependencies

f8a_worker/utils.py
fixes https://cucos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics-worker-master/433/console
=> Fix PostgresSessionWrapper

f8a_worker/workers/stackaggregator_v2.py
Hi
This PR is related to issue 192, for changing the default values and addition of a one more variable in sentiment part in stackaggregator_v2.py file.
Thanks,
Saket
=> fix for issue 192

f8a_worker/workers/recommender.py, requirements.in, requirements.txt
Reverts fabric8-analytics/fabric8-analytics-worker#204
=> Revert "introduce version filters"

f8a_worker/workers/recommender.py, requirements.in, requirements.txt
Reverts fabric8-analytics/fabric8-analytics-worker#205
=> Revert "Revert "introduce version filters""

f8a_worker/workers/graph_importer.py
=> Fix wrong error message in graph importer task

f8a_worker/graphutils.py
This PR contains the default values for overall_score and magnitude for sentiment analysis. These are required to pass the integration test.
Thanks,
Saket
=> update the default values of sentiment score and magnitude.

hack/install_owasp_dependency-check.sh
=> Update dependency-check to v2

f8a_worker/workers/digester.py, tests/workers/test_digester.py
see https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/175#issuecomment-319297899
=> [DigesterTask] compute digests of artifact only

f8a_worker/data_normalizer.py
Fixes:
```python
File "/usr/lib/python3.4/site-packages/f8a_worker/data_normalizer.py", line 482, in handle_data
result = switch.get(data['ecosystem'].lower(), _passthrough)(data.get('result', {})) 
File "/usr/lib/python3.4/site-packages/f8a_worker/data_normalizer.py", line 462, in _handle_dotnet_solution
separator = ',' if ',' in tags else ' '
TypeError: argument of type 'NoneType' is not iterable
```
=> [DataNormalizer._handle_dotnet_solution()] Handle empty/None attributes

f8a_worker/data_normalizer.py, f8a_worker/workers/license.py, tests/data/dataNormalizer/nuspec-expected
=>  [DataNormalizer/dotnet] use scancode to see what license is LicenseUrl pointing to

f8a_worker/object_cache.py
=> Log error instead of whole exception

f8a_worker/workers/keywords_tagging.py
=> Remove old parameter for keywords lookup

Dockerfile, tests/workers/test_sentiment_scorer.py
=> Separate google.protobuf hack and add test

f8a_worker/process.py, f8a_worker/utils.py, tests/test_utils.py
Fixes: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/182
=> Force use HTTPS when cloning git repos

Dockerfile, hack/workers.sh
check  http://$(hostname):8888/metrics
for available celery metrics
=> Add prometheus monitoring for celery

Dockerfile, hack/workers.sh
Reverts fabric8-analytics/fabric8-analytics-worker#281
=> Revert "Add prometheus monitoring for celery"

openshift/template.yaml
Threshold set in accordance with the recommendations for OSIO quick-start.
=> Update threshold for kronos comp_outlier

f8a_worker/conf.py, f8a_worker/schemas.py, f8a_worker/utils.py, f8a_worker/workers/digester.py
https://www.python.org/dev/peps/pep-3134
=> Use 'raise from' to have exception chaining

f8a_worker/models.py, f8a_worker/storages/package_postgres.py, f8a_worker/storages/postgres.py, f8a_worker/storages/postgres_base.py, f8a_worker/utils.py, f8a_worker/workers/gh_metadata_result_collector.py, f8a_worker/workers/result_collector.py
Fixes https://github.com/openshiftio/openshift.io/issues/681
Note that I was first trying to fix/improve the  PostgresSessionWrapper (see first commit), but it turned out to be not that elegant solution after all.
See commit messages at each commit to see more details.
=> Rework postgres session wrapping

Dockerfile, hack/install_tagger.sh
until tagger is mature enough to be in base image
=> [Dockerfile] move hack/install_tagger.sh from worker-base

f8a_worker/dispatcher/nodes.yml
=> Remove undefined graphApiImportFlow from nodes.yml

hack/install_tagger.sh
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/313
=> Bump tagger version

f8a_worker/workers/license.py, tests/workers/test_licensecheck.py
=> License error

Dockerfile
to pull in:
- mercator-1-20
- owasp-dependency-check-2.1.1
=> [Dockerfile] bump f8a-worker-base image hash

f8a_worker/utils.py, f8a_worker/workers/anitya.py, f8a_worker/workers/downstream.py
=> Use MavenCoordinates to convert to repo_url

f8a_worker/data_normalizer.py, f8a_worker/workers/mercator.py, tests/data/maven/com.networknt/mask/pom.xml, tests/workers/test_mercator.py
=> [MercatorTask] set MERCATOR_JAVA_RESOLVE_POMS=true again

f8a_worker/solver.py
=> [NugetReleasesFetcher] amend it to current nuget.org html code

f8a_worker/workers/bookkeeper.py, f8a_worker/workers/stackaggregator_v2.py
Symptomatic remedy of issue - https://github.com/openshiftio/openshift.io/issues/659.
=> Prevent HTTP error 500 for unresolved dependencies

f8a_worker/manifests.py, f8a_worker/workers/graphaggregator.py, f8a_worker/workers/mercator.py
(the last two commits are just code refactoring)
=> Don't resolve pom files when running mercator via API

openshift/template.yaml
Changes policy for workers from Rolling to Recreate.
Fix openshiftio/openshift.io#687
=> Change update policy to Recreate

f8a_worker/solver.py, f8a_worker/workers/graphaggregator.py, tests/test_solver.py
Fixes problem described in https://github.com/openshiftio/openshift.io/issues/659#issuecomment-330278723
=> [PypiDependencyParser] handle trailing '.*' in requirements.txt

f8a_worker/workers/graphaggregator.py
raises
`selinon.errors.FatalTaskError: Dependencies could not be resolved: '['foopackagebar==1.2.3']'`
instead of
`ValueError: Package foopackagebar not found`
Related to https://github.com/openshiftio/openshift.io/issues/850
=> [GraphAggregatorTask] better error when dependency solving fails

f8a_worker/data_normalizer.py, f8a_worker/dispatcher/foreach.py, f8a_worker/dispatcher/predicates.py, f8a_worker/dispatcher/selective.py, f8a_worker/graphutils.py, f8a_worker/manifests.py, f8a_worker/object_cache.py, f8a_worker/storages/s3.py, f8a_worker/utils.py, f8a_worker/workers/CVEchecker.py, f8a_worker/workers/bigquery_gh.py, f8a_worker/workers/bookkeeper.py, f8a_worker/workers/cvedbsync.py, f8a_worker/workers/finalize.py, f8a_worker/workers/graph_sync.py, f8a_worker/workers/oscryptocatcher.py, f8a_worker/workers/recommender.py, f8a_worker/workers/stackaggregator.py, f8a_worker/workers/stackaggregator_v2.py
=> Fix 'E722 do not use bare except'

f8a_worker/solver.py
See https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/355#issuecomment-332121924
=> Fix NugetReleasesFetcher

f8a_worker/workers/stackaggregator.py
Fixes https://github.com/openshiftio/openshift.io/issues/1026
=> Work-around for 'E722 do not use bare except'

README.md
Reverts fabric8-analytics/fabric8-analytics-worker#381
=> Revert "Debug CI"

Dockerfile, docs/worker_ecosystem_support.md, f8a_worker/data_normalizer.py, f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml, f8a_worker/dispatcher/nodes.yml, f8a_worker/object_cache.py, f8a_worker/process.py, f8a_worker/solver.py, f8a_worker/storages/__init__.py, f8a_worker/storages/s3_temp_artifacts.py, f8a_worker/storages/s3_userprofilestore.py, f8a_worker/utils.py, f8a_worker/workers/anitya.py, f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/libraries_io.py, f8a_worker/workers/mercator.py, tests/conftest.py, tests/test_data_normalizer.py, tests/test_solver.py
=> Add support for Golang

f8a_worker/workers/mercator.py
=> Capture test dependencies for Go in mercator

f8a_worker/workers/stackaggregator_v2.py
fixes https://github.com/openshiftio/openshift.io/issues/849
=> Fixes issue 'Unknown components' count 

f8a_worker/workers/mercator.py
Fix issue - https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/403
=> Resolve - F821 undefined name 'l'

README.md
This reverts commit 49cc4ee611f725b34d4280ebe3005f12ed8394d0.
=> Revert "CI debug"

f8a_worker/workers/stackaggregator_v2.py
Reverts fabric8-analytics/fabric8-analytics-worker#410
=> Revert "Revert "Fixes issue 'Unknown components' count""

f8a_worker/workers/repository_description.py
=> Fix AttributeError: 'NoneType' object has no attribute 'decompose'

f8a_worker/workers/recommender.py
https://github.com/openshiftio/openshift.io/issues/1213
=> fixes license failure issue

tests/test_solver.py
which won't be updated in future
=> [TestFetcher] Test GolangReleasesFetcher on forked repo

f8a_worker/workers/stackaggregator_v2.py
Replaced watchers with open issues and contributors hardcoded-ness is removed.
=> modify github descriptive data

cico_run_tests.sh, cico_setup.sh
https://github.com/openshiftio/openshift.io/issues/1257
=> Push images built from PRs to a registry

f8a_worker/solver.py
Fixes issue: https://github.com/openshiftio/openshift.io/issues/1394
=> Fix bug - ValueError: need more than 2 values to unpack

f8a_worker/base.py, f8a_worker/blackduck_helpers.py, f8a_worker/storages/postgres.py, f8a_worker/storages/s3_vulndb.py, f8a_worker/workers/dependency_snapshot.py, f8a_worker/workers/finalize.py, f8a_worker/workers/gh_metadata_init.py, f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/init_package_flow.py, f8a_worker/workers/keywords_tagging.py, f8a_worker/workers/recommender.py, tests/storages/test_postgres.py, tests/test_blackduck_helpers.py, tests/test_solver.py
see https://github.com/openshiftio/openshift.io/issues/1359
=> Use UTC in all timestamps

f8a_worker/dispatcher/nodes.yml, f8a_worker/storages/__init__.py, f8a_worker/storages/s3_crowd_source_tags.py
Related to https://github.com/openshiftio/openshift.io/issues/1270
=> crowd source tags cleaning

f8a_worker/storages/s3.py
Service with 2Gi of memory is getting OOM killed while uploading 650Mi
file.
=> Stream files from disk while uploading them to S3

f8a_worker/graphutils.py, f8a_worker/workers/recommender.py
Part of user-story https://github.com/openshiftio/openshift.io/issues/assigned/sara-02
=> [WIP]: Add key-value for component companion count

hack/create_flow_migration.sh, hack/exec_tests.sh, hack/generate-db-migrations.sh, hack/run-db-migrations.sh, hack/visualize_flows.sh, hack/worker+pmcd.sh, hack/worker-liveness.sh, hack/worker-queues-env.sh, hack/worker-readiness.sh
https://www.shellcheck.net
See commit messages for more details.
I checked after myself couple times and tried to test (locally and on dev cluster) most of the scripts, so it should be fine, but please review all changes - open each commit, so you can see the original `shellcheck` warnings.
=> Run hack/*.sh through Shellcheck

f8a_worker/graphutils.py
Fix strings, and dict formatting.
=> Minor refactoring

hack/queue_conf.py, hack/worker-pre-hook.sh, requirements.txt
Related to https://github.com/openshiftio/openshift.io/issues/1081
=> Tag SQS queues with DEPLOYMENT_PREFIX

f8a_worker/defaults.py, f8a_worker/workers/libraries_io.py, tests/workers/test_libraries_io.py
=> [LibrariesIoTask] move getting of project url to F8AConfiguration

f8a_worker/workers/README.md
Related to https://github.com/openshiftio/openshift.io/issues/2168
=> [workers/README.md] Update

f8a_worker/celery_settings.py, f8a_worker/dispatcher/predicates.py, f8a_worker/setup_celery.py, hack/create_flow_migration.sh, hack/visualize_flows.sh, hack/worker-queues-env.sh, requirements.in, requirements.txt
- Required minor changes in codebase
- Updated due to sentry support
=> Update to latest version of Selinon

Dockerfile, f8a_worker/defaults.py, f8a_worker/workers/CVEchecker.py, f8a_worker/workers/mercator.py, tests/data/go/mercator-go/main.go, tests/workers/test_cvecheck.py, tests/workers/test_mercator.py
Should fix https://github.com/openshiftio/openshift.io/issues/2222
=> [CVEcheckerTask] Set JVM memory limit before running dependency-check

openshift/template.yaml
It's not resolving Sentry DSN correctly.
=> There was missing dollar sign in template which is causing errors

f8a_worker/workers/CVEchecker.py, tests/workers/test_cvecheck.py
"Fixes": https://ci.centos.org/job/devtools-fabric8-analytics-worker-fabric8-analytics/545/consoleFull
The NIST website was down during the build.
=> [tests] Throw an exception on status code other than 200

f8a_worker/solver.py
luckily I wrote lots of unit tests for this part of code long time ago, so it should be fine once the tests pass
=> More Dependency.check() refactoring

f8a_worker/dispatcher/flows/osioAnalysisFlow.yml, f8a_worker/dispatcher/foreach.py, f8a_worker/dispatcher/nodes.yml, f8a_worker/workers/DependencyParserTask.py, f8a_worker/workers/UnknownDependencyFetcherTask.py
Experimental for GA task.Please do not merge.
=> dep ingester flow addeed

tests/workers/test_cvecheck.py
Because of https://github.com/fabric8-analytics/fabric8-analytics-cvedb-s3-dump-docker/pull/11
=> [TestCVEchecker] update expected data

tests/data/schemas/generate.py, tests/test_data_normalizer.py, tests/test_process.py, tests/test_utils.py, tests/workers/test_bigquery_gh.py, tests/workers/test_cvecheck.py, tests/workers/test_licensecheck.py, tests/workers/test_mercator.py
Thanks @abs51295 for pointing me to the pathlib
=> [tests] Use pathlib to get rid of all the ugly joins

alembic/versions/727aeeb88b2f_add_started_at_and_ended_at_to_.py
Fixes:
"Multiple head revisions are present for given argument 'head'"
=> [alembic] Keep just one head

f8a_worker/setup_celery.py
I was doing some unrelated experiments with this file and couldn't resist rewriting all the joins to pathlib :-)
Tested locally.
=> [setup_celery.py] Use pathlib

f8a_worker/workers/mercator.py
Fixes
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/542/
Better error message for
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/566/
=> [MercatorTask] Pypi related fixes

f8a_worker/data_normalizer.py, tests/data/dataNormalizer/npm-with-shrinkwrap-json-expected
Fixes
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/55643/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/54295/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/54094/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/54089/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/53933/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/565/
=> [DataNormalizer._handle_javascript()] fixes

f8a_worker/solver.py, tests/test_solver.py
https://errortracking.prod-preview.openshift.io/openshift_io/pkajaba-fabric8-analytics/issues/660/
=> ValueError in f8a_worker.solver in _extract_op_version

f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/init_package_flow.py
see https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-staging-kb/issues/482/
=> Less cryptic error when ecosystem is unknown

runtest.sh
[--link flag is legacy feature](https://docs.docker.com/network/links)
=> [runtest.sh] Define&use docker network instead of links between containers

f8a_worker/data_normalizer.py
see https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/605/
=> DataNormalizer:_join_name_email() fix

f8a_worker/utils.py
Fixes https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/800/
=> [utils:url2git_repo()] add scheme if missing

f8a_worker/defaults.py, f8a_worker/solver.py, tests/test_solver.py
https://docs.npmjs.com/misc/scope
Fixes
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/529/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/488/
=> [NpmReleasesFetcher & F8AConfiguration] handle npm's scoped packages

f8a_worker/utils.py
otherwise we fail later when trying to convert it to json:
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
Fixes
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/544/
=> [utils:get_response()] consider 204 (no content) as error

f8a_worker/solver.py, f8a_worker/workers/dependency_snapshot.py
reproducer: `maven:com.nimbusds:oauth2-oidc-sdk:5.56`
=> [MavenSolver] make sure resolved version is always string

f8a_worker/data_normalizer.py
Fixes:
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/611
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/621
=> More DataNormalizer._handle_javascript() fixes

f8a_worker/process.py
per
http://maven.apache.org/ref/3-LATEST/maven-model-builder/super-pom.html
=> [IndianaJones] update Maven Central Repository url

f8a_worker/data_normalizer.py, f8a_worker/workers/mercator.py
reproducer npm:subsetty:0.2.4
Fixes https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/1723/
=> [MercatorTask] ignore requirements.txt in node packages

f8a_worker/dispatcher/flows/osioAnalysisFlow.yml, f8a_worker/dispatcher/foreach.py, f8a_worker/dispatcher/nodes.yml, f8a_worker/graphutils.py, f8a_worker/workers/__init__.py, f8a_worker/workers/dependency_parser.py, f8a_worker/workers/graph_importer.py, f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/report_generation.py, f8a_worker/workers/unknown_dep_fetcher.py, tests/workers/test_github_dependency_tree.py
Add Report Generation Task to generate report for given github repository
- Task is responsible for generating report by getting descriptive statistics for dependencies identified by GithubDependencyTreeTask.
Add Unknown Dependency Fetcher Task to fetch unknown dependencies from dependencies identified by GithubDependencyTreeTask
- Task is responsible to identify unknown dependencies and pass them to bayesianApiFlow for ingestion.
=> Add Unknown Depndency Fetcher Task and Report Generation Task

f8a_worker/data_normalizer.py
Fixes:
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/1701/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/617/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/1709/
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/77419/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/78062/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/78114/
- https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/505/events/78156/
- …
=> Another round of DataNormalizer._handle_javascript() fixes

f8a_worker/workers/mercator.py
Signed-off-by: abs51295 <aagams68@gmail.com>
=> Fix to get only outermost requirements.txt

f8a_worker/dispatcher/flows/bayesianPackageAnalysisFlow.yml, f8a_worker/dispatcher/flows/bayesianPackageFlow.yml
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "package_worker_results"
violates foreign key constraint "package_worker_results_package_analysis_id_fkey"
DETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".
=> Fix the annoying integrity error

hack/install_tagger.sh
https://github.com/fabric8-analytics/fabric8-analytics-worker-base/commit/7365c673d4fe4cb2864a8d1f4475cb345f7f4eb7
=> moved this step to fabric8-analytics-worker-base

hack/install_tagger.sh
Reverts fabric8-analytics/fabric8-analytics-worker#605
=> Revert "moved this step to fabric8-analytics-worker-base"

f8a_worker/base.py, f8a_worker/errors.py, f8a_worker/storages/postgres_base.py
Fixes https://github.com/openshiftio/openshift.io/issues/3181
=> IntegrityError fix

Dockerfile
For: https://github.com/openshiftio/openshift.io/issues/3182
=> Bump worker-base image to f8a-worker-base:0bcf081

Dockerfile.rhel
For: https://github.com/openshiftio/openshift.io/issues/3182
=> Bump worker-base image to f8a-worker-base:0bcf081 for rhel

f8a_worker/workers/report_generation.py, f8a_worker/workers/unknown_dep_fetcher.py
- Set logging level to info to make it visible in logs.
=> Change logging level to info

f8a_worker/dispatcher/foreach.py
- To make sure that all the packages reach graph, force the analysis for packages absent in graph.
- This is a part of gemini flow since we want every package to reach graph.
=> Force package analysis for unknown packages

f8a_worker/data_normalizer.py, tests/test_data_normalizer.py
Ref Bug - https://github.com/openshiftio/openshift.io/issues/3406
Signed-off-by: Geetika Batra gbatra@redhat.com
=> Fix Value error for engines in _handle_javascript data.

f8a_worker/base.py, f8a_worker/storages/postgres_base.py, hack/workers.sh, requirements.in, requirements.txt
This commit fixes issue #3166 : https://github.com/openshiftio/openshift.io/issues/3166
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   f8a_worker/base.py
modified:   f8a_worker/storages/postgres_base.py
modified:   hack/workers.sh
modified:   requirements.txt
=> [SEV2] Fix missing audit log data for failed tasks

f8a_worker/solver.py
Update version parsing for nuget
=> Fix failing tests

alembic/script.py.mako
Check-style test will pass from now on. The problem will be with pylint test, because line length is usually more than 100 chars.
=> Changed Mako script template, so it will pass our pydoc check

f8a_worker/models.py, f8a_worker/utils.py
Fixes:
File "/usr/lib/python3.4/site-packages/f8a_worker/models.py", line 224, in package_info
from f8a_worker.utils import (get_package_dependents_count,
ImportError: cannot import name 'get_package_dependents_count'
=> Fix ImportError in models.py

f8a_worker/victims.py, tests/workers/test_cvecheck.py
Fixes: https://github.com/openshiftio/openshift.io/issues/3645
=> Fix version ranges support in Victims worker

.coveragerc, hack/exec_tests.sh, tests/requirements.in, tests/requirements.txt
The 1st approach of our CI job connection with codecov.io.
The results can be seen here:
https://codecov.io/gh/fabric8-analytics/fabric8-analytics-worker
=> Codecov.io setup

f8a_worker/workers/graph_importer.py
Signed-off-by: Geetika Batra gbatra@redhat.com
=> Update graph-importer worker with source_repo in arguments.

f8a_worker/defaults.py, f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml, f8a_worker/dispatcher/foreach.py, f8a_worker/storages/package_postgres.py, f8a_worker/storages/postgres.py, f8a_worker/utils.py, f8a_worker/workers/cvedbsync.py, f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/libraries_io.py, f8a_worker/workers/license.py, tests/workers/test_libraries_io.py
implements: openshift.io/issues/3698
=> Use EcosystemBackend

Dockerfile.tests, Makefile, f8a_worker/solver.py, runtest.sh, tests/test_solver.py
Fixes: https://github.com/openshiftio/openshift.io/issues/4055
=> [solver] Handle 'latest' version in NPM

f8a_worker/workers/report_generation.py
- Part of https://github.com/openshiftio/openshift.io/issues/4108
=> Add ecosystem at package level in ReportGenerationTask

f8a_worker/workers/victims.py
- Use endpoint instead of auth_server_url.
=> Fix variable name for auth url

openshift/template.yaml
Default is CentOS-based, but staging/prod runs RHEL-based.
=> [openshift] Fix image name

hack/exec_tests.sh
https://docs.pytest.org/en/latest/usage.html#modifying-python-traceback-printing
=> [exec_tests.sh] show locals in tracebacks

Dockerfile, f8a_worker/workers/git_operations.py, tests/workers/test_git_operations.py
Signed Off by: Geetika Batra <gbatra@redhat.com>
=> Changes parser from inbuilt class to f8a_utils

f8a_worker/workers/golangcvepredictor.py
Added tags sources, link and type
=> Changed Json Format in S3

f8a_worker/dispatcher/nodes.yml, f8a_worker/storages/postgres_base.py, tests/storages/test_postgres.py
Fixes: https://github.com/openshiftio/openshift.io/issues/4686
=> Fix another integrity error

f8a_worker/dispatcher/nodes.yml
This reverts commit 5590bd2d8ef24a5ccf4d6c9395b43095417ec46a.
=> Revert "No storage for GitOperationTask"

f8a_worker/workers/init_analysis_flow.py, f8a_worker/workers/init_package_flow.py, tests/workers/test_init_analysis_flow.py, tests/workers/test_init_package_flow.py
Related to https://github.com/openshiftio/openshift.io/issues/4702.
=> Improve strict assert checks in init tasks

check-docstyle.sh, cico_run_pydoc.sh, cico_run_pylint.sh, cico_setup.sh, detect-common-errors.sh, detect-dead-code.sh, run-linter.sh, runtest.sh, tools/check_python_version.py
=> Check Python version on CI

README.md, check-docstyle.sh, detect-common-errors.sh, detect-dead-code.sh, directories.txt, f8a_worker/schemas.py, files.txt, files_without_dead_code.txt, run-linter.sh
This PR implements the first task in:
https://jira.coreos.com/browse/APPAI-516
Make all QA-related tools more effective and easier to use by developers
1. All QA-related scripts needs to be made unified by using external list of directories to check
2. All QA-related scripts needs to be moved into separate subdirectory
3. QA Dashboard should be updated to use the new scripts (as #1)
JIRA issue for the 1st task:
https://jira.coreos.com/browse/APPAI-481
Currently, several QA-related scripts have the 'source-directories' included in the script body. It would be nice to use separate and central configuration file for this.
=> QA script use directories.txt

cico_build_deploy.sh
=> Fixed path to script

Dockerfile, Dockerfile.rhel, f8a_worker/workers/init_analysis_flow.py
This PR would prevent any pvt pkgs from getting into the ingestion flow.
=> changes to prevent pvt ingestion

f8a_worker/workers/init_package_flow.py
bayesian-worker-ingestion - IndexError: list index out of range
Fixes # (https://jira.coreos.com/browse/APPAI-955)
=> fix for appai 955 - index error

f8a_worker/workers/license.py
Fix for Jira issue: https://jira.coreos.com/browse/APPAI-949 (bayesian-worker-ingestion error - FatalTaskError: Error (137) during running command '/opt/scancode-toolkit/scancode)
=> Removed raising exception for unsuccessful scancode execution

README.md
Trigger CI for fabric-analytics-worker.
=> Trigger CI

openshift/template.yaml
Change secret naming based on new convention
=> change secret naming based on new convention

requirements.txt
Reverts fabric8-analytics/fabric8-analytics-worker#889
=> Revert "fix: CI Build Failing Issue"

MAINTAINERS
=> Trigger E2E

f8a_worker/workers/libraries_io.py, f8a_worker/workers/unknown_dep_fetcher.py, tests/workers/test_libraries_io.py
Fix for the schema validation error
=> libraries_io schema change

Dockerfile.rhel
Updating command to install selinon from binary is rhel dockerfile 
[APPAI-1359]
=> fix: Use custom selinon with patch to drain message if it is old

README.md
=> Dummy to trigger e2e

f8a_worker/utils.py, f8a_worker/workers/githuber.py, f8a_worker/workers/new_githuber.py, tests/workers/test_githuber.py
Added logic to collect data for missing github details for both new and old flows.
APPAI - 1608
1. Written common logic to be called from old and new ingestion flows.
2. Removed schema validation from old Github class. The version of schema has been changed and the fields added were part of old schema because of this, it is causing validation error. Since we are already creating JSON in format required by Data Importer we can avoid validation of schema in worker.
=> feat: Collect more Github statistics

README.md, qa/runtest.sh
Use minio from quay rather than docker hub to avoid pull limit errors
=> chore : Pull minio from quay instead of docker 

f8a_worker/storages/postgres.py, f8a_worker/workers/bookkeeper.py
A new fucntion has been added in component api flow to store data inside component analyses request table.
=> fix: Modify `ComponentApiFlow` to store data from CA post call into RDS

f8a_worker/utils.py, f8a_worker/workers/githuber.py
Updated tenacity retry statements, and using it in wrapper function "execute_gh_queries" as well. If "get_gh_query_response" fails for all 5 attempts "execute_gh_queries" will retry it again.
=> fix: Retry mechanism modified.

f8a_worker/workers/bookkeeper.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix: Add condition for strict check inside CA flow.

requirements.in, requirements.txt
=> chore: Update utils to latest.

build_deploy.rhel.sh, build_deploy.sh
=> fix: docker login before push

f8a_worker/utils.py
Reverts fabric8-analytics/fabric8-analytics-worker#969
=> Revert "chore: debugging"

f8a_worker/celery_settings.py
It was logging all the INFO and we can't upload this many logs to server
- changing logs configuration to ERROR so only error are printed
=> Changing logs configuration to ERROR

.github/workflows/ci-build.yml, qa/runtest.sh
- Python version failing to setup
=> Update python version
