fabric8-analytics/fabric8-analytics-worker

openshift/template.yaml
=> [openshift] Lower memory limit to 1GB

cucoslib/process.py, cucoslib/storages/s3_mavenindex.py, cucoslib/storages/s3_owaspdepcheck.py
Related to https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/46
=> Don't upload archive to S3 if zipping fails.

cucoslib/workers/license.py
If a license is found more than once in a file, then 'paths' contains the file more than one.
Remove the duplicates by using set.
=> Remove duplicate paths in license scanner output

cucoslib/workers/license.py
When `scancode` stops scanning any file due to reaching a timeout,
it continues to scanning next file, but the return code is `1`.
That's not what we want, because the task then fails (`graceful=True` is not a good idea here).
=> [LicenseCheckTask] increase --timeout value passed to scancode

f8a_worker/workers/git_stats.py
Fixes:
```
File "/usr/lib/python3.4/site-packages/f8a_worker/workers/git_stats.py", line 132, in execute
master_log = self._get_log(arguments['url'])
File "/usr/lib/python3.4/site-packages/f8a_worker/workers/git_stats.py", line 25, in _get_log
with tempdir as tmp_dir:
AttributeError: __exit__
```
=> Fix tempdir usage

f8a_worker/process.py, f8a_worker/workers/license.py
- Treat Python eggs as zip archives (fixes #112 )
- [LicenseCheckTask] ignore pyc files
=> Python egg

f8a_worker/solver.py, tests/test_solver.py
https://www.python.org/dev/peps/pep-0440/#compatible-release
This probably is already implemented somewhere in [pip](https://pypi.python.org/pypi/pip), but I haven't found it (to reuse that code).
=> PypiSolver - compatible release operator (~=)

Dockerfile, hack/pip-requirements.txt
I can't find what actually needs gofedlib.
If mercator-go, then the requirement should go into https://github.com/fabric8-analytics/mercator-go/blob/master/mercator.spec
If some worker, then it should go into requirements.in/txt
=> Remove hack/pip-requirements.txt

hack/patches/scancode_ignore_binary.patch
=> [hack/patches/scancode_ignore_binary.patch] skip files bigger than 1MB

f8a_worker/workers/dependency_snapshot.py
```python
File "/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py", line 100, in execute
self.log.info('resolved dependency %s as %s', resolved, dep)
UnboundLocalError: local variable 'resolved' referenced before assignment
```
=> [DependencySnapshotTask] Fix unbound local variable

f8a_worker/workers/libraries_io.py, tests/workers/test_libraries_io.py
The task was failing because of some white spaces around `'Total releases'`  in
https://libraries.io/nuget/NPOI and around `'Dependent projects'` in
https://libraries.io/nuget/Microsoft.jQuery.Unobtrusive.Ajax
=> [LibrariesIoTask] Use regexp for more general match

hack/install_deps_rpm.sh
To work-around the following problem:
```sh
$ docker run -ti centos:7 bash -c "yum install -y epel-release && yum install nodejs"
--> Finished Dependency Resolution
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
Requires: http-parser >= 2.7.0
```
See also https://bugzilla.redhat.com/show_bug.cgi?id=1481008
=> [hack/install_deps_rpm.sh] install http-parser from koji

f8a_worker/process.py
examples:
Bootstrap 3.3.6-jQuery3 -> bootstrap.3.3.6-jquery3.nupkg
Common.Logging 3.4.1-RC1 -> common.logging.3.4.1-rc1.nupkg
=> Version in nupkg download url needs to be lowercase

f8a_worker/process.py
'git clone' doesn't understand urls starting with: git+ssh, git+http, git+https
and fails with:
fatal: Unable to find remote helper for 'git+https'
[example](https://github.com/alleyinteractive/sasslint-webpack-plugin/blob/master/package.json#L17) of such url
=> Remove 'git+' from url before we 'git clone' it

tests/workers/test_libraries_io.py
examples of such fail:
https://cucos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics-worker-master/478/console
https://cucos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics-worker-PRs/370/console
https://cucos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics-worker-PRs/373/console
=> [test_libraries_io] mark TestLibrariesIoTask as expected to fail

f8a_worker/workers/CVEchecker.py
reverts f0f4831 and adds globing to find *.nuspec
=> [CVEcheckerTask] Direct DependencyCheck to nuspec

f8a_worker/data_normalizer.py
If there's no `'Repository'` tag and `'ProjectUrl'` contains Github repo url, use it as `code_repository`
=> [data_normalizer] reuse ProjectUrl as code_repository

Jenkinsfile
That's the test image name we [use in runtest.sh](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/runtest.sh#L16)
Or maybe I don't understand how it works now ?
=> Rename cucos-lib-tests to worker-tests

f8a_worker/solver.py, tests/test_solver.py
Even the PEP 440 says that its use is heavily discouraged.
Related to https://github.com/fabric8-analytics/fabric8-analytics-server/issues/104
=> [PypiDependencyParser] support arbitrary-equality operator

f8a_worker/process.py, f8a_worker/utils.py, f8a_worker/workers/githuber.py
Fixes #283 
The error/exception is still logged, but
- we don't wait for the `git clone` to timeout due to interactively asking for credentials
- the error message explicitly says what happened
=> Handle cloning of non-existent git repos

f8a_worker/workers/CVEchecker.py, tests/workers/test_cvecheck.py
The OSS Index does not provide CVSS score/vector/severity, so we need to get it from different source, which is easy once we know the CVE id.
=> [CVEcheckerTask] get CVSS score, vector and severity from NVD

openshift/template.yaml
according to docker stats, the container needs around 1.3-1.4GiB
when scancode toolkit is scanning some maven artifacts
Fixes #326
=> [openshift/template.yaml] increase memory limit to 1.5GiB

f8a_worker/workers/CVEchecker.py, f8a_worker/workers/cvedbsync.py
Example:
https://ossindex.net/v2.0/vulnerability/pm/maven/fromtill/1900000000000/-1
should return no results because the timestamp is way in future,
but for some reason there's always at least one entry.
Remove it - if its 'updated' time is lower than the specified 'from_time'.
=> ossindex 'bug'? work-around

f8a_worker/workers/CVEchecker.py
Fox example
https://ossindex.net/v2.0/package/maven/commons-fileupload
contains 4 CVEs, but each of them is in the `'vulnerabilities'` list 4 times.
=> [CVEcheckerTask] remove possible OSSIndex duplicates

f8a_worker/workers/recommender.py, f8a_worker/workers/stackaggregator_v2.py
Hi @miteshvp @pkajaba ,
Can you please review the license related changes in the worker ? There are mainly two changes:
1. Stack Aggregator v2 ( stackaggregator_v2.py ) now extracts details like unknown licenses, conflicting licenses, license outlier packages, etc. from the license analysis REST service.
2. Recommender ( recommender.py ) now filters PGM recommendations based on license i.e. we avoid recommending any package(s) that might result in conflict later if user chooses that package.
Thanks,
Harjinder
=> License filter and detailed output from license service

f8a_worker/workers/graphaggregator.py
Restore the previous behavior when [[1]](https://github.com/openshiftio/openshift.io/issues/1063) is done/in progress.
=> Always resolve POMs in mercator

f8a_worker/workers/recommender.py, f8a_worker/workers/stackaggregator_v2.py
Hi @miteshvp ,
Can you please review and merge the fix for license analysis and filter issue that we encountered on stage today ?
There are two fixes:
1) In recommender.py, I fixed how we access 'licenses' information for a 'version' vertex of graph.
2) In stackaggregator_v2.py, I fixed the string formatting issue.
Thanks,
Harjinder
=> Fix license analysis and filter

Dockerfile
See https://ci.centos.org/job/devtools-fabric8-analytics-worker-base-f8a-build-master/10/console for the hash.
=> Bump worker-base image to pull in gofedlib fixes.

tests/test_solver.py
Previously there was only one not sem-ver compliant version in
https://www.nuget.org/packages/System.Data.SQLite
Now they've replaced! 1.0.105.2 with 1.0.106 in version history.
Remove the test completely since 1.0.106 is sem-ver compliant.
=> [TestFetcher] Remove System.Data.SQLite

f8a_worker/workers/init_analysis_flow.py
The message already says it's maven.
=> No need to tell the ecosystem twice.

tests/workers/test_cvecheck.py
The entry that we check has been updated in NVD, therefore the output is
slightly different now.
=> [test] Fix CVECheck tests

f8a_worker/graphutils.py, f8a_worker/workers/recommender.py, f8a_worker/workers/stackaggregator_v2.py
Currently we show detected `licenses` on OSIO dashboard and license scoring also uses detected licenses to calculate stack license. It should be modified to use `declared_licenses`.
=> use declared_licenses instead of licenses (detected)

f8a_worker/storages/s3_crowd_source_tags.py
@miteshvp do I understand (from [this](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/445#discussion_r152192501)) it correctly that in https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/211 we want to:
- retrieve from `dev-stack-analysis-clean-data/<ecosystem>/github/data_input_raw_package_list/package_topic.json`
- store into `dev-stack-analysis-clean-data/<ecosystem>/github/data_input_raw_package_list/crowd_sourcing_package_topic.json`
?
=> [storages/S3CrowdSourceTags] retrieve package_topic.json

hack/queue_conf.py, hack/worker-pre-hook.sh
When testing https://github.com/fabric8-analytics/fabric8-analytics-common/pull/446 I realized that only '_api_' queues are configured during deployment.
This PR reverts c671b4dfd748, which I think causes the problem.
The `worker-pre-hook.sh` change had been added due to the `sleep(1/5)` in `queue_conf.py`, but we actually don't need either, since I've tested that SQS is able to properly handle many tagging requests per second - I created a script which tries to tag queues in parallel processes without any sleeping and all queues were tagged correctly.
=> revert 'Reuse WORKER_RUN_DB_MIGRATIONS to configure SQS queues only from one pod.'

tests/workers/test_githuber.py
The following API call:
```
https://api.github.com/licenses/bsd-3-clause
```
returns:
```
name | "BSD 3-Clause \"New\" or \"Revised\" License"
```
ie "Clause" has uppercase "C"
=> Reflect the changes on GitHub side

f8a_worker/workers/CVEchecker.py, f8a_worker/workers/csmock_worker.py, f8a_worker/workers/dependency_snapshot.py, f8a_worker/workers/githuber.py, f8a_worker/workers/mercator.py, f8a_worker/workers/oscryptocatcher.py
Let selinon handle exceptions instead of masking them into `{'status': 'error'}`.
Fixes https://github.com/openshiftio/openshift.io/issues/2150
=> Unify error handling

f8a_worker/workers/CVEchecker.py
`TimedCommand.get_command_output()` returns `[]` if there's a problem and `graceful` is `True` (which it is by default).
=> [CVEcheckerTask] Don't upload dep-check db if update fails

f8a_worker/data_normalizer.py, f8a_worker/solver.py, f8a_worker/storages/s3_mavenindex.py, f8a_worker/storages/s3_vulndb.py, f8a_worker/utils.py, f8a_worker/workers/CVEchecker.py, f8a_worker/workers/cvedbsync.py, f8a_worker/workers/git_stats.py, f8a_worker/workers/graphaggregator.py, f8a_worker/workers/mercator.py, tests/workers/test_cvecheck.py
utils.tempdir is probably some Python 2 relic
Python-3.4's [tempfile.TemporaryDirectory](https://docs.python.org/3.4/library/tempfile.html#tempfile.TemporaryDirectory) should work exactly the same
=> Remove utils.tempdir and use tempfile.TemporaryDirectory instead

f8a_worker/dispatcher/flows/osioAnalysisFlow.yml, f8a_worker/dispatcher/nodes.yml, f8a_worker/process.py, f8a_worker/utils.py, f8a_worker/workers/__init__.py, f8a_worker/workers/dependency_parser.py
Resolves task 3 of [#2326](https://github.com/openshiftio/openshift.io/issues/2326).
=> Add dependency parser task for maven

hack/generate-db-migrations.sh, runtest.sh
Fixes:
```
Starting/creating containers:
+ docker run -d --env-file tests/postgres.env --name worker-tests-db-2018-03-01-16-28-51 registry.centos.org/sclo/postgresql-94-centos7:latest
Unable to find image 'registry.centos.org/sclo/postgresql-94-centos7:latest' locally
Trying to pull repository registry.centos.org/sclo/postgresql-94-centos7 ... 
Pulling repository registry.centos.org/sclo/postgresql-94-centos7
/usr/bin/docker-current: Error: image sclo/postgresql-94-centos7:latest not found.
```
Unlike https://registry.centos.org/centos/postgresql-94-centos7 the https://registry.centos.org/sclo/postgresql-94-centos7 is empty.
Not sure why we've been using the 'sclo' variant, but the tests as well as generating db migrations run OK with the 'centos' one.
For the one failing test see #541
=> Use centos/postgresql-94-centos7 instead of sclo/postgresql-94-centos7

f8a_worker/dispatcher/flows/bayesianPackageFlow.yml
The results from tasks that finished successfully were never stored on S3 if there was an error later on.
=> Store available results on S3, regardless of failure

f8a_worker/workers/__init__.py, f8a_worker/workers/dependency_parser.py, tests/workers/test_github_dependency_tree.py
=> Test GithubDependencyTreeTask

f8a_worker/process.py, tests/test_process.py
`git clone repo dir/` deletes `dir/` if cloning fails. There's no option to turn this off.
This might confuse caller of the method, who could want to delete the dir itself.
Therefore we recreate the dir/ on error.
Example where this happens is [GitStats._get_log()](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/git_stats.py#L28)
See https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-analytics-production/issues/705/
which fails with cryptic `No such file or directory: '/tmp/tmpkllc_dvr'` instead of self-explaining `'Unable to clone: https://github.com/babel-plugins/babel-plugin-langpack'`
=> [Git.clone()] recreate dir on error if previously existed

f8a_worker/defaults.py
It should be shown only when LIBRARIES_IO_TOKEN == 'no-token'
=> Fix misplaced warning

f8a_worker/start.py
Fixes issue with `NameError: name 'raven' is not defined`
=> NameError: name 'raven' is not defined

f8a_worker/workers/dependency_parser.py
I tried the task on non-maven repo and got empty `TaskError`.
=> [GithubDependencyTreeTask] maven-dependency-plugin writes errors to stdout, not stderr

f8a_worker/workers/report_generation.py
Perform semantic_version.Version.coerce() to convert any version-like string into a valid semver version. Read https://python-semanticversion.readthedocs.io/en/latest/#coercing-an-arbitrary-version-string.
=> Perform semantic_version.Version.coerce() 

f8a_worker/workers/mercator.py
- Fixes the problem of getting empty dependencies because they are not popped anymore!
Signed-off-by: abs51295 <aagams68@gmail.com>
=> Use get() instead of pop() to get the dependencies

f8a_worker/workers/init_package_flow.py
`document_id` has a very special meaning in package level flows,
so make sure we don't run around with the one inherited from parent flow.
=> Fix another integrity error issue in package level flows

Dockerfile, f8a_worker/manifests.py, f8a_worker/solver.py, hack/install_tagger.sh
Using Pip's internal API is exactly what we SHOULDN'T be doing, but we also don't want to reimplement the logic on our own. We want to parse requirement.txt files exactly as the native tool, Pip, would parse them.
We will see how this goes.
=> Migrate to pip 10

f8a_worker/workers/dependency_parser.py, tests/workers/test_github_dependency_tree.py
- Currently, mercator only supports npm-shrinkwrap.json and hence we need a hack to support package-lock.json as of now.
- Need to revert this once mercator supports package-lock.json.
Signed-off-by: abs51295 <aagams68@gmail.com>
=> Add support for package-lock.json file for GithubDependencyTreeTask

f8a_worker/workers/dependency_parser.py
- Parse Gopkg.lock file via anymarkup to gather all direct and transitive dependencies along with their versions.
- Parse glide.lock file via mercator to gather all direct and transitive dependencies along with their versions.
- Add a failover mechanism for osioAnalysisFlow so that ReportGenerationTask is called irrespective of failures.
=> Add go support for GithubDependencyTreeTask

.gitignore, Dockerfile, Dockerfile.rhel, Makefile, cico_build_deploy.sh, cico_run_tests.sh, cico_setup.sh
Enable build on RHEL if TARGET=rhel.
As part of an effort to migrate the services running in OSIO from CentOS
to RHEL, we are ready to push out the RHEL based image for this service
into staging.
This PR includes a new RHEL based dockerfile for the deployment of the service.
This dockerfile will be built when this variable is set: TARGET=rhel. The build
scripts have been adapted to take this into consideration, and to push the image
to different namespaces if the TARGET is rhel or not.
Currently the deployment builds happen on empty baremetal machines. The build
script will be executed a second time to build and push the deployment file if
TARGET=rhel, so some changes in the build script are to ensure that it will work
if executed a second time.
=> Deploy on RHEL based container

f8a_worker/errors.py, f8a_worker/start.py
This PR is creating an exception which is inherited from `TaskError`. It means that once you throw this exception flow will end, but it will be ignored by a Sentry.
=> Create non-error exception for further Sentry integration

Dockerfile, Dockerfile.rhel, Dockerfile.tests, Makefile, cico_setup.sh, openshift/template.yaml
This PR is part of the effort to move to Quay.
This is the list of changes in this PR:
- Pushes to Quay instead of the Devshift registry
- Uses an image hosted in Quay to build the RHEL based container image
- Uses the new env-toolkit to load variables from jenkins-env
- Changes the default path of the image to quay (note that this should
not affect production because it is overridden in the saas repo)
A companion PR should have been submitted to the appropriate saas repo
to change the staging url from devshift to quay. The PR to the saas
repo should be merged before this one.
https://github.com/openshiftio/saas-analytics/pull/417
=> Move to Quay.io

f8a_worker/data_normalizer.py, tests/data/dataNormalizer/npm-with-shrinkwrap-json-from-mercator
Fixes:
{'version': '', 'runtime': '', 'name': '@hint/hint-no-broken-links',
'lockfileVersion': 1, 'dependencies': []}
is not valid under any of the given schemas
=> Fix mercator output for certain shrinkwrap files

f8a_worker/workers/dependency_parser.py, f8a_worker/workers/report_generation.py, f8a_worker/workers/unknown_dep_fetcher.py, tests/workers/test_github_dependency_tree.py
- Adds a flag 'lock_file_absent' and returns a json response instead of raising a TaskError if lock file is absent in the repository during scanning.
=> Notify gemini about missing lock file

f8a_worker/storages/postgres.py
Fixes:
psycopg2.IntegrityError: duplicate key value violates unique constraint "api_requests_pkey"
=> Don't throw an exception if we process the same API request multiple times

f8a_worker/storages/postgres.py
SQLAlchemyError is a base class for IntegrityError
=> Catch IntegrityError first, before SQLAlchemyError

f8a_worker/storages/s3.py, f8a_worker/storages/s3_gocveartifact.py, tests/storages/test_s3_gocveartifact.py
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
Since March 1, 2018, Amazon S3 no longer supports creating bucket names
that contain uppercase letters or underscores.
=> Fix bucket name for S3IssuesPRs storage

f8a_worker/data_normalizer/javascript.py, tests/data_normalizer/javascript.py
Previously it could have been "" (empty string).
=> Make sure "declared_licenses" field is None if there is no license

requirements.txt
Bumping up GitPython version because of https://github.com/gitpython-developers/GitPython/issues/983 
[CI Build is Failing- ModuleNotFoundError: No module named 'gitdb.utils.compat'](https://ci.centos.org/job/devtools-f8a-server-backbone-fabric8-analytics/448/consoleFull).
=> Bumping up GitPython version

requirements.txt
Adding gitdb2 dependency because gitdb: Transitive Dep of Worker has lost access to Pypi account. 
https://github.com/gitpython-developers/GitPython/issues/983 
Reverting [Bumping up gitpython](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/887) because of Failed E2E
https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/2429/consoleFull
[CI Build is Failing- ModuleNotFoundError: No module named 'gitdb.utils.compat'](https://ci.centos.org/job/devtools-f8a-server-backbone-fabric8-analytics/448/consoleFull).
=> fix: CI Build Failing Issue

f8a_worker/workers/libraries_io.py
spdx_expression and original_license were 2 additional unwanted fields coming in the library_io response. The same has been ignored.
=> schema validation failed error rectification

f8a_worker/dispatcher/flows/bayesianAnalysisFlow.yml, f8a_worker/dispatcher/flows/bayesianPackageAnalysisFlow.yml
Removed source_licenses and libraries_io tasks from the flow, as these are not in use anymore.
=> Removal of source_licenses and libraries_io tasks from ingestion flow

f8a_worker/utils.py, f8a_worker/workers/githuber.py, requirements.txt
Github API by default gives 30 contributors list, to get actual list of contributors we need to use pagination over URL. to do this added a utility function to iterate over pages unless length of list is not 0.
APPAI-1432
=> fix: Incorrect github repo contributor count

openshift/template.yaml
As CI deployment job does not accept value of a environment variable as a Numeric type, making the value a String object.
=> fix: Define SQS_MSG_LIFETIME as oc template parameter

f8a_worker/defaults.py, f8a_worker/dispatcher/nodes.yml, f8a_worker/utils.py, f8a_worker/workers/githuber.py, f8a_worker/workers/new_githuber.py, f8a_worker/workers/new_init_package_analysis_flow.py, f8a_worker/workers/new_init_package_flow.py, tests/workers/test_new_init_package_analysis_flow.py, tests/workers/test_new_init_package_flow.py
In existing implementation one token is selected and used for all Github API calls so sometimes we end up exceeding rate limit of Github API.
To avoid that different token is used for each API call. 
Fixes:  
APPAI-1725
Changes:
=> fix: Github statistics collection.

Dockerfile.app-sre, Dockerfile.rhel.app-sre, build_deploy.rhel.sh, build_deploy.sh
As part of https://issues.redhat.com/browse/APPSRE-3082 we are migrating the service to App SRE standards.
We are duplicating the Dockerfiles to pull and push to quay.io/app-sre and this will be cleaned up in a following PR.
Thanks!
=> Add App SRE build scripts and Dockerfiles

openshift/template.yaml
part of https://issues.redhat.com/browse/APPSRE-3082
this PR adds a ServiceAccount to the deployment manifest so that the pods can pull a private image. the pull secret is currently associated to the default ServiceAccount, and that is not a good practice.
=> add pull secret to openshift manifest

openshift/template.yaml
follow up on #951 
since the same template is applied multiple times and we only allow unique resources to be applied, the SA name should be unique.
=> make SA name unique in template

openshift/template.yaml
the changes introduced will not work since the pre hook pod of the DeploymentConfig is only using the default SA, which doesn't have pull credentials.
we will need to take a different route (new PR incoming).
=> revert template SA changes

openshift/template.yaml
part of https://issues.redhat.com/browse/APPSRE-3082
to allow all pods created by a DeploymentConfig to pull private images, we need to add this section to the template. using a ServiceAccount does not work because the pre hook pod is using the default SA and this is not overridable (AFAIK).
=> add imagePullSecrets to DeploymentConfig

f8a_worker/utils.py, f8a_worker/workers/githuber.py
for some repositories Github API uses full name, and it is causing API to fail, to avoid it full name of repo is taken from metadata of repository.
Also retry mechanism is modified while calling any GH API.
=> fix: Repo name and retry mechanism
